version: '3'
services:
  hadoop:
    image: sequenceiq/hadoop-docker:latest
    container_name: hadoop
    ports:
      - "50070:50070"  # Namenode HTTP
      - "8088:8088"    # ResourceManager HTTP
      - "50075:50075"  # Datanode HTTP
    environment:
      - CLUSTER_NAME=mycluster
    volumes:
      - hadoop_namenode:/namenode
      - hadoop_datanode:/datanode

  hive-metastore:
    image: bde2020/hive-metastore-postgresql:latest
    container_name: hive-metastore
    ports:
      - "9083:9083"
    environment:
      - INIT_HIVE_METASTORE=true
    depends_on:
      - hadoop

  trino:
    image: trinodb/trino
    container_name: trino
    ports:
      - "8080:8080"
    environment:
      - "HIVE_METASTORE_URI=thrift://hive-metastore:9083"
    depends_on:
      - hive-metastore

volumes:
  hadoop_namenode:
  hadoop_datanode:

